### ISSUE TITLE
taalswitcher

### ISSUE THREAD

**Issue by roxannewyns** [libis/VDIC#63]
VDIC vindt het niet gebruiksvriendelijk dat de knoppen met de taalkeuze linksboven telkens naar de homepage verwijzen.  Ze willen liever dat ze op dezelfde pagina blijven en switchen naar de andere taal van die pagina 

(Als je bijv. op de NL pagina "Databanken" bent en je klikt op FR, dan zou je rechtstreeks naar de FR pagina Databanken moeten gaan (en niet naar de FR homepage).)

@samalloing Is dit mogelijk?

**Comment by JorisLambrechts** [comment]
fix https://github.com/libis/VDIC/commit/dd6868c0bba5a5fcb2c9dec98b5f2efc4cc51ccf
