### ISSUE TITLE
saven item geeft blank page

### ISSUE THREAD

**Issue by roxannewyns** [libis/VDIC#81]
Bij het saven van een item krijg je een blank page. De wijzigingen lijken wel bewaard als je dan terug gaat met de browser.

**Comment by JorisLambrechts** [comment]
https://github.com/libis/VDIC/commit/0b81356ebdabbbd21a55b2d21959da1f80735e73 (verkeerde nummer gecommit, 18 ipv 81)

**Comment by roxannewyns** [comment]
heb je al gecommit? ik krijg nog steeds een blank page.

**Comment by JorisLambrechts** [comment]
Moest nog deployen, excuses. Nu moet het wel in orde zijn.
